### ISSUE TITLE
Charsets not handled with contentTypes

### ISSUE THREAD

**Issue by melvincarvalho** [linkeddata/node-webid#15]
It seems in many cases contentType contains a charset : 

https://www.w3.org/International/articles/http-charset/index

However this would appear to break node-webid with a rather cryptic error message.  This means that many webids will fail to log in to an unpatched node solid server, leading to inconsistent behaviour and possible user frustration

Possible code to fix may be along the lines of :  

    if (mimeType && mimeType.length) {
      mimeType = mimeType.split(';')[0]
    }

At : https://github.com/linkeddata/node-webid/blob/master/lib/parse.js#L7

**Comment by elf-pavlik** [comment]
solid-web-client solved it in this PR https://github.com/solid/solid-web-client/pull/12

rdflib.js also now seems to handle that: https://github.com/linkeddata/rdflib.js/pull/167

**Comment by webr3** [comment]
fixed at root level in $rdf.parse to ensure consistent behaviour

**Comment by melvincarvalho** [comment]
Just an update on this issue.

I have tested with the latest node solid server which uses the latest rdflib 0.15.0 however the error still remains

> solid:authentication Error processing certificate: undefined

**Comment by elf-pavlik** [comment]
node-webid itself has old version of rdflib as dependency

https://github.com/linkeddata/node-webid/blob/master/package.json#L47
`"rdflib": "^0.2.6"`
